all:
	g++ -std=c++11 -g -Wall -O3 ex1.cpp -o ex1 -I../include -L../lib -lmimixfe -lasound
	g++ -std=c++11 -g -Wall -O3 ex2.cpp -o ex2 -I../include -L../lib -lmimixfe -lasound
	g++ -std=c++11 -g -Wall -O3 ex3.cpp -o ex3 -I../include -L../lib -lmimixfe -lasound

